apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniblog.postgresql.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "miniblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.secret.user }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.secret.password }}
  POSTGRES_DB: {{ .Values.postgresql.secret.database }}
