{
 "title": "MiniBlog Monitoring Dashboard",
 "tags": [
  "devops",
  "fastapi"
 ],
 "panels": [
  { "title": "MiniBlog Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests Rate (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (endpoint, method)",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (http_status)",
     "legendFormat": "Status {{http_status}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) by (endpoint) / sum(rate(http_request_duration_seconds_count[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}} avg latency"
    }
   ]
  },
  {
   "title": "Total Blog Posts Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "posts_created_total", "legendFormat": "Total Posts" }
   ]
  }
 ]
}