apiVersion: v2
name: miniblog
description: MiniBlog - A blog application with FastAPI backend, PostgreSQL, and Nginx frontend
type: application

# Chart version (tăng khi thay đổi template)
version: 1.0.0

# App version (tăng khi deploy version mới)
appVersion: "1.0.0"

keywords:
  - blog
  - fastapi
  - postgresql
  - nginx

maintainers:
  - name: DevOps Team
    email: devops@example.com
