apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniblog.backend.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "miniblog.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "miniblog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "miniblog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.backend.securityContext.runAsUser }}
        runAsGroup: {{ .Values.backend.securityContext.runAsGroup }}
        fsGroup: {{ .Values.backend.securityContext.fsGroup }}
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgresql.secret.user }}:{{ .Values.postgresql.secret.password }}@{{ include "miniblog.postgresql.fullname" . }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.secret.database }}"
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: {{ .Values.backend.securityContext.runAsUser }}
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probes.liveness.periodSeconds }}
